#Base Image
FROM node:21-alpine

RUN apk add procps
# Set Working Directory
WORKDIR /app

# Copy Package Files
COPY package*.json ./  

# Copy All Files
COPY . .

# Cant run here as we need MySQL to be up Run Prisma Migrations and Generate Client
# RUN npx prisma migrate dev --name init
# RUN npx prisma generate

RUN rm -rf node_modules
RUN npm install -g pnpm
RUN pnpm install  # Install only production dependencies for efficiency

# Build Nuxt Application
RUN npm run build

# Run the application
CMD [ "pnpm", "run", "dev", "--no-fork"]
# Debug
# CMD [ "pnpm", "run", "dev", "--inspect"]
