version: '3.8'

services:
 # MySQL service
  db:
    build:
      context: ./mysql # Path to your Node.js/Nuxt.js project directory
      dockerfile: Dockerfile # Name of your Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'movienest'
      MYSQL_USER: 'your_user'
      MYSQL_PASSWORD: 'Password'
      MYSQL_ROOT_PASSWORD: 'your_root_password'
      # Mount the initialization script
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql # Persist database data
  nuxt:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'mysql://root:your_root_password@db:3306/movienest'
      # SHADOW_DATABASE_URL: 'mysql://root:your_root_password@db:3306/movienest_shadow'
    command: ["sh", "-c", "npx prisma migrate dev --name init && npx prisma generate && npx prisma migrate deploy && node .output/server/index.mjs"]
      
volumes:
  mysql_data: # Named volume for MySQL data persistence
